### ISSUE TITLE
org-alert-interval issue

### ISSUE THREAD

**Issue by ovc** [spegoraro/org-alert#11]
`(require 'org-alert)`
`(org-alert-enable)`
`(setq org-alert-interval 14400)`
`(setq alert-default-style 'libnotify)`

Why `(setq org-alert-interval 14400)` didn't work, interval still 300s.
And how to set `org-alert-headline-regexp` to "Deadline" only?
Thank you!

**Comment by spegoraro** [comment]
For the interval problem you're having, you need to set the interval before enabling org-alert:
```
(setq org-alert-interval 14400)
(org-alert-enable)
```
This is because the function `org-alert-enable` calls `run-at-time` with the _current_ value of `org-alert-interval`.

The deadline-only regex you're after:
```
(setq org-alert-headline-regexp "Deadline:.+")
```

If you ever need to play with elisp-style regexps use `M-x regexp-builder`.
