### ISSUE TITLE
Notification raised for the days scheduled items, after scheduled time, on every `org-alert-check` call

### ISSUE THREAD

**Issue by jackson15j** [spegoraro/org-alert#28]
Not sure if this is a problem with my config: https://github.com/jackson15j/dot_emacs/blob/master/config.org#org-alert, but on a Maverick Macbook I am seeing my scheduled alerts being re-raised after a scheduled event's time. It is happening every time `org-alert-check` is called.

Reproduction:

* Create an org heading in an agenda file.
* Schedule (`C-cC-s`) it to an earlier time in the past.
* Call the org alert check (`M-x org-alert-check`).
* Notification for past event occurs.

Expectations:

* Notifications **are not** sent for a scheduled event if time to event is **greater than** `org-alert-notify-cutoff` value.
* Notifications **are** sent for a scheduled event if time to event is **less than** `org-alert-notify-cutoff` value.
* Notifications **are not** sent for a scheduled event if time is after the scheduled time.

Config snippet from above link:

```lisp
(use-package org-alert
  :ensure-system-package terminal-notifier
  :ensure t
  :after (org)
  :config
  (setq
   alert-default-style 'notifier
   )
  (org-alert-enable)
  )
```

**Comment by jackson15j** [comment]
Note: notifications are not raised after the scheduled time, if the heading is marked as DONE.

My workflow is to work on scheduled items for a period and then mark as DONE if the work is completed. Only just added `org-alert`, so now seeing repeat notifications while I'm actively working on a scheduled task.

**Comment by ntBre** [comment]
Personally the continued notifications until I mark the heading as DONE are exactly what I want since I only use my agenda to schedule events and keep a separate todo list for actually doing them. Have you considered introducing an intermediate TODO state between TODO and DONE? In your case you could call it WORK or something. Then you can mark ongoing work as WORK to stop notifications.

Alternatively, I guess I could add a configurable variable to say if you want the notifications to continue past some window around the event. Would that fix the issue?

**Comment by jackson15j** [comment]
I like the either of a variable to configure behaviour. eg.

* `org-alert-notify-after-event-start = <True|False>`.
* `org-alert-notify-after-event-cutoff = <int>` in minutes.

I think that's a clean way to support both of Our workflows.

---

On the workflow front I have TODO's and appointments in my Agenda file, for a unified view. I've also set notifications from `terminal-notifier` to be Alerts (present until dismissed) instead of Banners (disappear after 5 seconds) to match Teams/Outlook when they are notifying appointments.

For example:

* Create a 1hr appointment in both Teams & Org-Agenda.
* Teams raises 1 notification X minutes before the meeting. Notification has to be dismissed.
* Org-Alert (default settings) raises a notification every 5 minutes, from 10 minutes before the meeting, until (one of):
    * the end of the day.
    * the heading is marked as DONE.
    * the heading is deleted.

Adding as context for my assumptions/expectations. Not to say that it should only work the same as Teams/Outlook. Hope that helps.

**Comment by ntBre** [comment]
Thanks for the context and the great initial report! I think adding such a variable is a really minor change to enable more workflows, so I'll take a look today. I thought it was more involved initially, which is why I brought up the TODO stuff. I think I'll probably go for the `after-event-cutoff` and use a default value of `nil` that preserves the original behavior. I'll definitely add something to the README showing how to change it, though.

I might have to look into banner-style notifications myself too.

**Comment by ntBre** [comment]
Just added `org-alert-notify-after-event-cutoff` in f1801e0. I still need to write a little test suite for the package, so it's not tested, but hopefully the code was simple enough I didn't mess it up. Please let me know if you run into any issues, and I will reopen this. Thanks again for the report!

**Comment by jackson15j** [comment]
Just updated from `melpa` and can confirm that with `org-alert-notify-after-event-cutoff 1`, I am no longer getting repeat notifications >1min after a scheduled event.

Thanks so much for the quick turnaround on this!!
