### ISSUE TITLE
use libnotify by default for alert-default-style

### ISSUE THREAD

**Issue by danielkrajnik** [spegoraro/org-alert#32]
Right now by default org-alert outputs to message buffer instead of doing what literally any sane person would expect it to do. I think that it would be useful if it didn't do that.

**Comment by ntBre** [comment]
If you double-check the variable you're talking about (`alert-default-style`), you'll see that it's actually provided by the [alert.el package](https://github.com/jwiegley/alert), which we depend on. I do agree with you, especially for the use case I have for `org-alert`, but because it's not our code, I think the best we can do is point this out in the README, which we do.

Personally I'm quite interested in dropping `alert.el` entirely and using the built-in [notifications](https://www.gnu.org/software/emacs/manual/html_node/elisp/Desktop-Notifications.html) package. I think that would also handle #31. However, the only backwards-compatible way I can see to do that is by still depending on `alert.el` and leaving it as the default notification backend, which would again require the user to change a variable.

**Comment by danielkrajnik** [comment]
Oh my, I'm sorry. You are right, I've closed the issue.

Thank you for mentioning the notifications package. I've just tested it (e.g. `(notifications-notify  :title "Title" :body "This is <b>important</b>." :actions '("Confirm" "I agree" "Refuse" "I disagree") :on-action 'my-on-action-function :on-close 'my-on-close-function)`) and it works really well out of the box.

Do you know by any chance how to set up notifications for org-mode/org-agenda tasks? If you have done it and would be okay with sharing your configurations I would really appreciate that. I've scanned the entire internet and there is absolutely zero examples how org-notifications (or any notifications package) should work. Any hints would be really helpful!

**Comment by ntBre** [comment]
@danielkrajnik, no problem at all, I found the interaction between these packages very confusing at first too, especially since we pull in `alert.el` as a dependency and you (probably) never explicitly installed it.

Anyway, could you give a little more detail about what you're trying to do? I use org-alert to send notifications for my org-agenda tasks, so it sounds like it should do what you want.

This is my whole org-alert config (mixed with some stuff from `alert.el`):

```emacs-lisp
(use-package org-alert
  :ensure t
  :config
  (setq alert-default-style 'libnotify
	    org-alert-interval 60
	    alert-persist-idle-time 0
	    alert-fade-time 600
	    org-alert-match-string "SCHEDULED<\"<yesterday>\"+SCHEDULED<\"<tomorrow>\"")
  (org-alert-enable))
```

and I set my `org-agenda-files` to the one file I want `org-alert` to look in:

```emacs-lisp
(setq org-agenda-files (list my-schd-file))
```

`my-schd-file` is just a simple path: "~/schedule.org".

`org-alert` calls `org-map-entries` with the `SCOPE` argument of `'agenda`, which tells `org-mode` to look through your `org-agenda-files`.

For a final bit of context, my `schedule.org` file looks like

```text
* DONE attend seminar
  SCHEDULED: <2023-07-24 Mon 15:00>
```

and I generate entries in there with `org-capture-templates`, this one in particular:

```emacs-lisp
(setq org-capture-templates
      '(("s" "Schedule")
	("ss" "Schedule" entry (file my-schd-file)
	 "* TODO %^{task}\n  SCHEDULED: %^T")))
```

There's an extra level of indirection there because I have multiple schedule types, but I wanted to paste as close to what I have as possible to avoid typos. I'd love to get more people using this package, so if this helps (or you have more questions) please let me know. I should pull this information into some kind of tutorial too if it helps.

**Comment by danielkrajnik** [comment]
Thank you very much for the detailed explanation. I've been trying for the past hour to get it to work, but it still doesn't seem to pick it up. Running `(require 'org-alert)` started to flood notifications, but unfortunately I couldn't control it. I'm on doom-emacs and had to modify your configuration slightly:

```
(use-package! org-alert
  :defer t
  :config
  (setq alert-default-style 'libnotify
        org-alert-interval 60
        alert-persist-idle-time 0
        alert-fade-time 60
        org-alert-match-string "SCHEDULED<\"<yesterday>\"+SCHEDULED<\"<tomorrow>\"")
  (org-alert-enable)
  )
```

**Comment by danielkrajnik** [comment]
Thank you very much for the detailed explanation - it helped a lot! 

**UPDATE:** after a third run it stopped working. Not sure what's going on. I've realized though that org-alert only notifies you the moment an event starts - I was looking for a system that notifies you some time BEFORE an event happens.

why oh why emacs ecosystem is so scrappy 😞...

_I think I finally (after an hour) found a way to get it to work. 
Being on doom emacs in situations like this makes it much much harder though:_
````
(use-package! org-alert
  :ensure t
  :config
  (setq alert-default-style 'libnotify
        org-alert-interval 60
        alert-fade-time 60
        org-alert-match-string "SCHEDULED<\"<yesterday>\"+SCHEDULED<\"<tomorrow>\"")
  (org-alert-enable)
  )
````
Which is almost exactly the same as your configuration, only except for `!` . I've never had to use `use-package!` macro before, but if I understand correctly it ensures that org-alert gets loaded. Any other configuration e.g. `defer: t` or just `(require 'org-alert)` didn't seem to work (require flooded notifications with hundreds of alerts). 

I think that doom emacs comes with org-alert by default, so no need to add `(package! org-alert)` to `packages.el` (but I may be wrong).

---

One thing I haven't worked out yet - do you know if there is a way to have multiple reminders for the same task, as well? For example, a day before, an hour before and 15 minutes before an event? 

---

> some kind of tutorial too

if you could that would be immensely helpful. I could find very few resources on notifications for org-mode tasks - no idea why and this is such an important part of staying organized. If you could share your tips and recommendations how to integrate org-alert that would be amazing. I have spent over four hours already trying to set this up ;/

**Comment by danielkrajnik** [comment]
> some kind of tutorial too

I've said it before, but this needs to be really emphasized. There are currently NO resources how to set this up. ANYTHING would be useful.

**Comment by ntBre** [comment]
Oof, yeah when Doom Emacs is involved I don't really know what to do. This probably isn't the place even to mention this, but my blanket recommendation is to start with default Emacs and build it up with stuff you want instead of a framework like Doom that obfuscates a lot. That obfuscation can make it seem easy at the very beginning, but I've gotten tons of questions from people trying to customize Doom Emacs beyond the initial stuff.

Anyway, feel free to ignore that rant. Getting back to your questions, what do you mean by "after a third run it stopped working"? You should just run `org-alert-enable` once and it should keep running for the rest of your Emacs session. You and I both do that as part of our `use-package` calls. I have no idea how Doom Emacs handles packages, but it sounds a little bit like it includes a very old version of `org-alert` (I'm honestly quite surprised it would include any version, I didn't think this was a very popular package). Before I started maintaining it, the behavior was like you describe: only notify when the event starts and flood you with notifications after the start.

Now, the default `org-alert-notify-cutoff` is 10 minutes, so you should be notified 10 minutes before your event. One thing to watch out for, though, is the default `org-alert-interval` of 5 minutes (300 seconds). In my config I set that to 60 seconds to poll a little more frequently. In the worst case that should give you a notification about 9 minutes before the event (if you hit the absolute worst case scenario of polling 1 second before 10 minutes and have to wait another minute to poll again). There is also `org-alert-notify-after-event-cutoff`, which you can set to a number of minutes after the event to *stop* sending notifications. It defaults to `nil`, which is again some backwards-compatibility.

Finally, unfortunately we don't yet support multiple notifications. I've left #18 open because I think it addresses that idea, but I haven't implemented it yet. I fairly recently added support for a per-item cutoff (bddb342), which might help in some cases, though.

**Comment by danielkrajnik** [comment]
Sorry, it still doesn't seem to work: `Error (use-package): Failed to parse package org-alert: use-package: Unrecognized keyword: :never-persist`

**Comment by ntBre** [comment]
> > some kind of tutorial too
> 
> I've said it before, but this needs to be really emphasized. There are currently NO resources how to set this up. ANYTHING would be useful.

I'm not trying to be rude (I think that should be evident from the rest of the thread), but the README includes very clear installation and configuration instructions, and the docstrings embedded in the package are useful as well, in my opinion. From my perspective, it seems like you don't know very much about Emacs packages (and maybe Emacs in general). Again, I don't want to put you off from using Emacs or this package, but as far as I can tell these issues have very little to do with our package.

**Comment by ntBre** [comment]
> Sorry, it still doesn't seem to work: `Error (use-package): Failed to parse package org-alert: use-package: Unrecognized keyword: :never-persist`

This is clearly some kind of Doom issue because it's injecting this `:never-persist` keyword argument not present in any of the code I've sent. You may need to take this up with the Doom developers or their documentation.

**Comment by danielkrajnik** [comment]
thank you very much for all the help. I'm sorry, but I may have to give up for now, at the end of the day I'm just looking for a notifications like in a typical calendar app (so multiple-notifications would be necessary) . I'm sure there are a lot of other use cases for org-alert and your advice helped me a lot to get in the right direction. 

UPDATE: if anyone stumbles upon this thread and finds themselves in the same situation here is the way I solved it:

```
(after! org
    (org-wild-notifier-mode)
    (setq alert-default-style 'notifications
              org-wild-notifier-alert-time '(0)
              org-wild-notifier-keyword-whitelist nil)
```
